export type ProfileProps = {
  id?: string;
  avatar_url?: string;
  bio?: string;
  birthday?: Date;
  books?: string;
  education?: string;
  first_name: string;
  gender?: string;
  hobbies?: string;
  interests?: string;
  is_drinker?: boolean;
  is_smoker?: boolean;
  is_stoner?: boolean;
  job_title?: string;
  last_name?: string;
  movies?: string;
  music?: string;
  personality_type?: string;
  political_affiliation?: string;
  profile_is_valid?: boolean;
  relationship_type?: string;
  religion?: string;
  tagline?: string;
  tv_shows?: string;
  updated_at?: Date;
  website?: string;
};
